
```{r}
devtools::install_github("cutterkom/generativeart")
install.packages("ambient")
```

```{r}
library(tidyverse)
library(generativeart) 
library(ambient)
```
```{r}

# set the paths
IMG_DIR <- "img/"
IMG_SUBDIR <- "everything/"
IMG_SUBDIR2 <- "handpicked/"
IMG_PATH <- paste0(IMG_DIR, 
                   IMG_SUBDIR)
LOGFILE_DIR <- "logfile/"
LOGFILE <- "logfile.csv"
LOGFILE_PATH <- paste0(LOGFILE_DIR, 
                       LOGFILE)
# create the directory structure
generativeart::setup_directories(IMG_DIR, 
                                 IMG_SUBDIR, 
                                 IMG_SUBDIR2, 
                                 LOGFILE_DIR)
```
```{r}
# include a specific formula, for example:
my_formula <- list(
  x = quote(runif(1, -1, 10) * x_i^2 - sin(y_i^2)),
  y = quote(runif(1, -1, 10) * y_i^3 - cos(x_i^2) * y_i^4)
)
```
```{r}
# call the main function to create five images with a polar coordinate system
generativeart::generate_img(formula = my_formula, 
                            nr_of_img = 5, # set the number of iterations
                            polar = TRUE, 
                            filetype = "png", 
                            color = "gold", 
                            background_color = "navy")
```

```{r}
library(jasmines)
jasmines_num <- 0
```
```{r}
p0 <- use_seed(48) %>% # Set the seed of R‘s random number generator, which is useful for creating simulations or random objects that can be reproduced.
  scene_discs(
    rings = 5000, 
    points = 5000, 
    size = 50
  ) %>%
  mutate(ind = 1:n()) %>%
  unfold_warp(
    iterations = 55,
    scale = .5, 
    output = "layer" 
  ) %>%
  unfold_tempest(
    iterations = 50,
    scale = 1
  ) %>%
  style_ribbon(
    color = "gold",
    colour = "ind",
    alpha = c(5,5),
    background = "blue"
  )

jasmines_num <- jasmines_num + 1

file_name <- paste0("img/jasmines/jasmines",jasmines_num,".png", collapse='","')


ggsave(file_name, p0, width = 20, height = 20, units = "in")
```


```{r}
library(mathart) # devtools::install_github("marcusvolz/mathart")
# library(ggart) # devtools::install_github("marcusvolz/ggart")
library(ggforce)
library(Rcpp)
library(tidyverse)
```
```{r}
points <- mathart::points
result <- kdtree(points)
p1 <- ggplot() +
  geom_segment(aes(x, y, xend = xend, yend = yend), result) +
  coord_equal() +
  xlim(0, 10000) + ylim(0, 10000) +
  theme_blankcanvas(bg_col = "#fafafa", margin_cm = 0)
# save plot
ggsave("kdtree.png", p1, width = 20, height = 20, units = "in")
```
```{r message=FALSE}
points <- mathart::points
result <- kdtree(points)
p1 <- ggplot() +
  geom_segment(aes(x, y, xend = xend, yend = yend), result) +
  coord_equal() +
  xlim(0, 10000) + ylim(0, 10000) +
  theme_blankcanvas(bg_col = "#fafafa", margin_cm = 0)
# save plot
ggsave("kdtree.png", p1, width = 20, height = 20, units = "in")
```


```{r}
# Metropolis: Generative city visualisations
# Packages
library(ggart)
library(tidyverse)
library(tweenr)
library(viridis)
# Make reproducible
set.seed(10001)
```
```{r}
# Parameters
n <- 10000 # iterations
r <- 75 # neighbourhood
width <- 10000 # canvas width
height <- 10000 # canvas height
delta <- 2 * pi / 180 # angle direction noise
p_branch <- 0.1 # probability of branching
initial_pts <- 3 # number of initial points
nframes <- 500 # number of tweenr frames
# Initialise data frames
points <- data.frame(x = numeric(n), y = numeric(n), dir = numeric(n), level = integer(n))
edges <-  data.frame(x = numeric(n), y = numeric(n), xend = numeric(n), yend = numeric(n), level = integer(n))
if(initial_pts > 1) {
  i <- 2
  while(i <= initial_pts) {
    points[i, ] <- c(runif(1, 0, width), runif(1, 0, height), runif(1, -2*pi, 2*pi), 1)
    i <- i + 1
  }
}
t0 <- Sys.time()
# Main loop ----
i <- initial_pts + 1
while (i <= n) {
  valid <- FALSE
  while (!valid) {
    random_point <- sample_n(points[seq(1:(i-1)), ], 1) # Pick a point at random
    branch <- ifelse(runif(1, 0, 1) <= p_branch, TRUE, FALSE)
    alpha <- random_point$dir[1] + runif(1, -(delta), delta) + (branch * (ifelse(runif(1, 0, 1) < 0.5, -1, 1) * pi/2))
    v <- c(cos(alpha), sin(alpha)) * r * (1 + 1 / ifelse(branch, random_point$level[1]+1, random_point$level[1])) # Create directional vector
    xj <- random_point$x[1] + v[1]
    yj <- random_point$y[1] + v[2]
    lvl <- random_point$level[1]
    lvl_new <- ifelse(branch, lvl+1, lvl)
    if(xj < 0 | xj > width | yj < 0 | yj > height) {
      next
    }
    points_dist <- points %>% mutate(d = sqrt((xj - x)^2 + (yj - y)^2))
    if (min(points_dist$d) >= 1 * r) {
      points[i, ] <- c(xj, yj, alpha, lvl_new)
      edges[i, ] <- c(xj, yj, random_point$x[1], random_point$y[1], lvl_new)
      # Add a building if possible
      buiding <- 1
      valid <- TRUE
    }
  }
  i <- i + 1
  print(i)
}
edges <- edges %>% filter(level > 0)
sand <- data.frame(alpha = numeric(0), x = numeric(0), y = numeric(0))
perp <- data.frame(x = numeric(0), y = numeric(0), xend = numeric(0), yend = numeric(0))
# Create plot
p2 <- ggplot() +
  geom_segment(aes(x, y, xend = xend, yend = yend, size = -level), edges, lineend = "round") +
  #geom_segment(aes(x, y, xend = xend, yend = yend), perp, lineend = "round", alpha = 0.15) +
  #geom_point(aes(x, y), points) +
  #geom_point(aes(x, y), sand, size = 0.05, alpha = 0.05, colour = "black") +
  xlim(0, 10000) +
  ylim(0, 10000) +
  coord_equal() +
  scale_size_continuous(range = c(0.5, 0.5)) +
  #scale_color_viridis() +
  theme_blankcanvas(bg_col = "#fafafa", margin_cm = 0)
# print plot
ggsave("plot007w.png", p2, width = 20, height = 20, units = "cm", dpi = 300)
```

